### ISSUE TITLE
Difference between this repo and xero-netstandard-oauth2-samples

### ISSUE THREAD

**Issue by Nothing-Works** [XeroAPI/xero-netstandard-oauth2-starter-dotnet-core#2]
@jenksguo Hi a general question, can you please talk about the difference between this repo the this one https://github.com/XeroAPI/xero-netstandard-oauth2-samples ?

I can see they are both for asp.net core. and the other one has more configurations in `Startup.cs` file (do I need to do it? as your one is much simpler). Can you briefly explain the differences? Which one should I follow?

Many thanks in advance.

**Comment by jenksguo** [comment]
Hi @Nothing-Works, thanks for asking this question. I am glad you asked. 

The repo mentioned here was made by our Xero developer @MJMortimer before we even made this SDK for demonstrate to user how to interface with Xero OAuth 2.0 & SSO in a "vanilla" way. It uses a very good MS package called Microsoft.AspNetCore.Authentication which is better managed and has way less code to maintain. 

This shows developers that they are not bound to use our SDK's OAuth 2.0 client and can use any package they like to interface with Xero OAuth 2.0. :-) 

Any more questions, please feel free to ask.

**Comment by Nothing-Works** [comment]
@jenksguo thanks for your time. It helps a lot.
